# Generated by Django 4.0.2 on 2022-03-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание ответа')),
                ('replyDate', models.DateTimeField(auto_now=True, verbose_name='дата получения ответа')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='tasks.task', verbose_name='связанная задача')),
            ],
            options={
                'verbose_name': 'Таблица с описанием ответа',
                'verbose_name_plural': 'Таблица с описанием ответа',
                'ordering': ('-replyDate',),
            },
        ),
        migrations.CreateModel(
            name='AnswerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='task_answer/')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerimages', to='answer.answer', verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'Таблица с изображениями ответа',
                'verbose_name_plural': 'Таблица с изображениями ответа',
            },
        ),
    ]
